### ISSUE TITLE
assess the usage of event topology.updated

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/kytos-sdx-topology#20]
Hi,

Kytos generates the event `topology.updated` when the topology is updated due to link up/down, interfaces up/down, and many other situations. I wonder why this event is not included in the list of Admin/Oper events. One think I can imagine is that we will try to handle the underling events, i.e.  the events which actually generated the topology.updated. However, I'm not quite sure we dont have the risk of losing information.

**Comment by lmarinve** [comment]
We want to start with specific events, observe the behavior, then add incremental events to test.
