### ISSUE TITLE
Cron Task for Periodic SDX Topology Updates to SDX-LC Every 30 Seconds

### ISSUE THREAD

**Issue by lmarinve** [atlanticwave-sdx/kytos-sdx-topology#35]
Objective:
To enhance the reliability and timeliness of the SDX topology updates, we need to implement a cron job that automatically sends the updated SDX topology to the SDX-LC (SDX Lifecycle Controller) every 30 seconds.

Background:
Currently, updates to the SDX topology need to be consistently pushed to the SDX-LC, leading to potential delays and mismatches in the SDX-LC processes data. Automating this process ensures that the SDX-LC always has the most current topology data without manual intervention.

Implementation Details:

Cron Schedule: The cron job should be set to run at 30-second intervals.
Task Operations: Each execution should:
Retrieve the latest SDX topology data.
Format the data as required by the SDX-LC API specifications.
Use an HTTP POST request to send the formatted topology to the SDX-LC's designated endpoint.
Error Handling: Implement robust error handling to manage and log any data retrieval or transmission failures.
Logging: Include detailed logging for each step to aid in debugging and ensure traceability of the data sent.
Expected Benefits:

Accuracy and Consistency: Ensures that the SDX-LC uses the most accurate and up-to-date topology information.
Automation: Reduces the need for manual updates and checks, increasing operational efficiency.
Reliability: Improves the overall reliability of the SDX network management by minimizing human error and data latency.

**Comment by italovalcy** [comment]
Hello @lmarinve , SDX-LC already has something like this. Why don't we leverage that existing code on SDX-LC to accomplish the reliability enhancements discussed here? Is there something new being addressed here?

Ccing @congwang09 and @YufengXin so they can provide more insights about the future plans for the pulling component on SDX-LC.

**Comment by lmarinve** [comment]
Thank you Italo, I am closing this issue since we will handle it in sdx-lc.
